before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Ugxu7KEBg7nulLB4wFQxxNENT59kQaO9mQwfRQmhw+B1fbG9QQfGW1nyDNGxvNIw6G0A6dJNzXbpoEMqSyWy6cuTF0HnxwgSxxSEU4pVS0WJBGCAZF3nBis+1clUwIiijnCswpRwd3rfUqUm32jUhGfTB253hq2BIG/HFIogq5j9VQ1RskeV2fWodFqOjQIYk9fCAGwGoRBFmc7/srTGUFLGGXnIMgl0aG5T9JQCoPJ+arhZMFf8pZImvSMmbJ/JCPEO/mJClMAAbhM3q19CqE/bcXlA1hve3Gv7XRFtbGws/lRYLEiUxLyUSAiU8c2ehlOdatzard4KyZQqoILPWhFVpiAsLekbBfch3NR6FU0w/NtsPFa8VirZHbFLlFB3X6oiAFtBYgxHnE1mmVeSPZNSCySLuXlOv1+8e/G9vkQ5UCtPGIpY7gaoUDWSKZb90pL0qfW9bRQyUoeoTDs/fy3qaQeX4s7oplvfYSt7glFvNFkcDpH+PSsgVq5cztdoGyMyN2czDeDCAtyCGNLkArWKn9R2Pp3sxPlJ2UU4faOF2t/TCMGNT41i1BIbWG4s1nGg0yQ3uONUdMmlv+tbogZwV4SwDonaCsG2DSYXFeZNSLpYCnhR+iRNCYQwEiNft4cBEAX5tDIjFDfU3H0x7TcO/qwpWy/eFtd1WZdKdus= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
